---
- name: Install Apache and PHP on Red Hat OS
  hosts: centos
  become: true
  tasks:
    - name: Install Apache and PHP packages
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
    
    - name: Start and enable httpd service
      systemd:
        name: httpd
        state: started
        enabled: yes
    
    - name: Open firewall port for HTTP
      firewalld:
        port: 80/tcp
        state: enabled
        permanent: yes
        immediate: yes
